# Generated by Django 3.2.6 on 2021-09-08 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departments',
            old_name='DepartmentId',
            new_name='department_id',
        ),
        migrations.RenameField(
            model_name='departments',
            old_name='DepartmentName',
            new_name='department_name',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='DateOfHire',
            new_name='date_of_hire',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='EmployeeId',
            new_name='employee_id',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='EmployeeName',
            new_name='employee_name',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='PhotoFileName',
            new_name='photo_file_name',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='Department',
        ),
        migrations.AddField(
            model_name='employees',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MainApp.departments'),
            preserve_default=False,
        ),
    ]
